### ISSUE TITLE
快更，等着看

### ISSUE THREAD

**Issue by lazyFrogLOL** [N402/N402.github.io#1]

**Comment by shonenada** [comment]
How old are you .

**Comment by lazyFrogLOL** [comment]
秒回也是醉了。。。。。。。。。。。。。。

**Comment by shonenada** [comment]
Standby.

**Comment by lazyFrogLOL** [comment]
猴

**Comment by lazyFrogLOL** [comment]
## 原来提交Issue可以用Markdown格式
- 这真是极好的
- 唉，又孤陋寡闻了

![img](http://ww1.sinaimg.cn/bmiddle/61e89b74jw1enrra5h36bj20ls0ewq56.jpg)
